### ISSUE TITLE
update Makefile

### ISSUE THREAD

**Issue by Choudoufuhezi** [DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis#38]
Based on tasks that are As we have removed the cross-validation section from the analysis, in response to the feedback received during milestone 1, the most recent version of model_workflow.py no longer creates the cross-validation result table, therefore: 

- Please remove the paths within the Makefile that pertain to generating the table mentioned. Additionally, ensure that the Makefile produces the expected results accurately.

**Comment by svs1607** [comment]
Makefile has been updated to reflect the above changes.
