### ISSUE TITLE
Feedback Addressed

### ISSUE THREAD

**Issue by svs1607** [DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis#46]
1. Addressing feedback on Milestone 1, update the project license to include a creative license for the non-software components. 
2. From feedback on the Peer Review, edit the script that saves train_data.csv to create a new directory if one does not exist. 
3. Following feedback on Milestone 2, edit the size of the images so that they are not too large (this needs to be edited by editing the EDA_workflows.py script). 
4. Addressing feedback on the Peer Review to review and modify the Dockerfile to ensure that the container is running properly. Also edit the README accordingly.
5. Addressing feedback on the Peer Review to include sufficient documentation through the form of docstrings in the function.
6. Adding the results to the report following the Peer Review feedback.

**Comment by svs1607** [comment]
Point 5 complete. Docstrings have been added to all the functions. The updated versions of the functions can be found in the [package repository](https://github.com/DSCI-310-2024/pycricketpred/tree/main/src/pycricketpred). The original functions had docstrings but were inconsistent in formatting and not all functions had them (as can be seen in the [Milestone 3 release](https://github.com/DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis/tree/2.0.0/src))

**Comment by svs1607** [comment]
Point 1 has been addressed. The License in the Milestone 1 [release](https://github.com/DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis/blob/0.0.1/LICENSE) does not include a License for the report. The latest version of the [license](https://github.com/DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis/blob/main/LICENSE) contains the Creative Commons License for the report.

**Comment by Choudoufuhezi** [comment]
Point 3 has been addressed. Plots within qmd file has been restricted to 90% of it's original width and height.

**Comment by svs1607** [comment]
Point 6 has been addressed. The [old](https://github.com/DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis/blob/2.0.0/reports/main_report.qmd) quarto report did not contain the final accuracy or the confusion matrix. This has been updated in the [new](https://github.com/DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis/blob/update_package/reports/main_report.qmd) report and includes these details. It can be found in the **Discussion** section.

**Comment by svs1607** [comment]
Point 4 has been addressed. The [old](https://github.com/DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis/blob/2.0.0/Dockerfile) Dockerfile did not contain `vegafusion-python-embed`, which was mentioned in the peer review. This has been added in the [new](https://github.com/DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis/blob/main/Dockerfile) Dockerfile

**Comment by alexlin519** [comment]
point 2, I addressed the save train data path, to catch error: create new dir if not exist.And this changed is under branch [update_package](https://github.com/DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis/pull/60). This changed is also in sync into the package repository.
