### ISSUE TITLE
Shift Files From Original Repository

### ISSUE THREAD

**Issue by Choudoufuhezi** [DSCI-310-2024/DSCI-310-Group-11-Cricket-Analysis#50]
Move all the function and test files to the package repository once all feedback has been addressed.

**Comment by svs1607** [comment]
All files have been added to the package repository. Once everything is published and updated, the src and tests need to be removed from the original analysis repository.

**Comment by svs1607** [comment]
The `src` and `tests` directories have been deleted from the original analysis repository.
